FROM debian:bookworm

# Install Python and other tools needed for testing
# RUN apt-get update && apt-get install -y \
#     python3 \
#     python3-pip \
#     bash \
#     && rm -rf /var/lib/apt/lists/*
#
# # Set Python 3 as the default python
# RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

CMD ["/bin/bash"]
